#!/usr/bin/env python
import json
from pathlib import Path
from stactools.noaa_nwm import stac
import kerchunk.hdf

href = "https://noaanwm.blob.core.windows.net/nwm/nwm.20231010/short_range/nwm.t00z.short_range.channel_rt.f001.conus.nc"
indices = kerchunk.hdf.SingleHdf5ToZarr(href).translate()
item = stac.create_item(href, kerchunk_indices=indices)

with open("examples/example-item/example-item.json", "w") as f:
    json.dump(item.to_dict(), f, indent=2)



# import shutil

# import stactools.noaa_nwm.stac
# from pystac import CatalogType

# root = Path(__file__).parents[1]
# examples = root / "examples"

# collection = stactools.noaa_nwm.stac.create_collection()
# item = stactools.noaa_nwm.stac.create_item(str(root / "tests" / "data" / "asset.tif"))
# collection.add_item(item)
# collection.update_extent_from_items()
# collection.normalize_hrefs(str(examples))
# collection.make_all_asset_hrefs_relative()
# if examples.exists():
#     shutil.rmtree(examples)
#     examples.mkdir()
# collection.save(CatalogType.SELF_CONTAINED)
